2020-08-10 01:46:25,462 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:46]
2020-08-17 16:20:49,980 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:52]
2020-08-17 20:13:47,065 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:66]
2020-08-17 20:13:59,909 ERROR: Exception on / [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "C:\Users\tonyy\blog\app\main\routes.py", line 15, in before_request
    g.locale = str(get_locale())
NameError: name 'get_locale' is not defined
2020-08-17 20:16:13,387 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:66]
2020-08-17 20:16:15,976 ERROR: Exception on / [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "C:\Users\tonyy\blog\app\main\routes.py", line 15, in before_request
    g.locale = str(get_locale())
NameError: name 'get_locale' is not defined
2020-08-17 20:16:54,468 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:66]
2020-08-17 20:16:57,507 ERROR: Exception on / [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tonyy\blog\app\main\routes.py", line 33, in index
    return render_template('index.html', title=_('Home'), form=form,
NameError: name '_' is not defined
2020-08-17 20:16:59,621 ERROR: Exception on / [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tonyy\blog\app\main\routes.py", line 33, in index
    return render_template('index.html', title=_('Home'), form=form,
NameError: name '_' is not defined
2020-08-17 20:17:00,472 ERROR: Exception on /index [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tonyy\blog\app\main\routes.py", line 33, in index
    return render_template('index.html', title=_('Home'), form=form,
NameError: name '_' is not defined
2020-08-17 20:17:01,769 ERROR: Exception on /index [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tonyy\blog\app\main\routes.py", line 33, in index
    return render_template('index.html', title=_('Home'), form=form,
NameError: name '_' is not defined
2020-08-17 20:17:02,553 ERROR: Exception on /index [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tonyy\blog\app\main\routes.py", line 33, in index
    return render_template('index.html', title=_('Home'), form=form,
NameError: name '_' is not defined
2020-08-17 20:22:54,874 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:66]
