2020-08-17 20:29:46,481 ERROR: Exception on /auth/login [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\tonyy\blog\app\auth\routes.py", line 27, in login
    return render_template('auth/login.html', title=('Sign In'), form=form)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\tonyy\blog\virtual\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\tonyy\blog\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\tonyy\blog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\tonyy\blog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\tonyy\blog\app\templates\auth\login.html", line 12, in block "app_content"
    <p>New User? <a href="{{ url_for('main.register') }}">Click to Register!</a></p>
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\tonyy\blog\virtual\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.register'. Did you mean 'auth.register' instead?
2020-08-17 22:00:23,935 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:66]
2020-08-17 22:02:37,621 ERROR: Exception on /index [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\login_manager.py", line 174, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\tonyy\blog\virtual\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'Please log in to access this page'. Did you mean 'main.edit_profile' instead?
2020-08-17 22:02:39,085 ERROR: Exception on /index [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\login_manager.py", line 174, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\tonyy\blog\virtual\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'Please log in to access this page'. Did you mean 'main.edit_profile' instead?
