2020-08-17 22:10:41,809 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:66]
2020-08-17 22:10:53,873 ERROR: Exception on /user/cat12 [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tonyy\blog\app\main\routes.py", line 62, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\tonyy\blog\virtual\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\tonyy\blog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\tonyy\blog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\tonyy\blog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\tonyy\blog\app\templates\user.html", line 24, in block "app_content"
    <form action="{{ url_for('main.unfollow', username=user.username) }}" method="post">
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\tonyy\blog\virtual\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.unfollow' with values ['username']. Did you mean 'main.follow' instead?
2020-08-17 22:12:43,363 ERROR: Exception on /user/cat12 [GET] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tonyy\blog\app\main\routes.py", line 62, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\tonyy\blog\virtual\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\tonyy\blog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\tonyy\blog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\tonyy\blog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\tonyy\blog\app\templates\user.html", line 24, in block "app_content"
    <form action="{{ url_for('main.unfollow', username=user.username) }}" method="post">
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\tonyy\blog\virtual\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.unfollow' with values ['username']. Did you mean 'main.follow' instead?
2020-08-17 22:16:10,741 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:66]
2020-08-17 22:16:34,755 ERROR: Exception on /index [POST] [in c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tonyy\blog\virtual\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\tonyy\blog\app\main\routes.py", line 18, in index
    language=language)
NameError: name 'language' is not defined
2020-08-17 22:17:12,021 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:66]
2020-08-17 22:17:56,331 INFO: Blog startup [in C:\Users\tonyy\blog\app\__init__.py:66]
